# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 02:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0097_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='changed_staging_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
